//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CellStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deals
    {
        public int Id { get; set; }
        public int SellerID { get; set; }
        public int Type { get; set; }
        public int Price { get; set; }
        public string Data { get; set; }
    
        public virtual Sellers Sellers { get; set; }
    }
}
