//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CellStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phones
    {
        public int Id { get; set; }
        public int Manufacturer { get; set; }
        public string Name { get; set; }
        public int Memory { get; set; }
        public double Price { get; set; }
        public int SimCount { get; set; }
        public int SdCard { get; set; }
        public int NFC { get; set; }
        public int FingerPrint { get; set; }
        public int FaceID { get; set; }
        public double Camera { get; set; }
    }
}
